[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "salp-rs"
version = "0.2.0"
description = "A Rust library with a python wrapper that allows fetching and (processing) big PDB data via queries by communicating with the RCSB API "
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "fragilefort", email = ""}]
dependencies = [
    "patchelf>=0.17.2.4",
    "twine>=6.1.0",
]

[tool.maturin]
python-source = "python"
module-name = "salp.salp_rs"
